import React, { useMemo, useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "../../lib/supabaseClient";
import { TOKENS } from "../../styles/tokens";

import { z } from "zod";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";

import {
  Plus,
  Search,
  Trash2,
  Pencil,
  Eye,
  X,
  Save,
  ArchiveRestore,
} from "lucide-react";

/**
 * teachers table columns (from your screenshot):
 * - user_id (uuid, PK/FK auth.users.id) -> GENERATED BY SYSTEM (not editable in UI)
 * - employee_number (varchar) -> GENERATED BY FRONTEND (T-YY-0001) (not editable)
 * - department (varchar)
 * - position (varchar)
 * - status (varchar)
 * - first_name (varchar)
 * - last_name (varchar)
 * - email (varchar)
 * - contact_number (varchar)
 * - is_archived (bool)
 * - created_at (system)
 * - updated_at (system)
 */

const teacherSchema = z.object({
  employee_number: z.string().min(1, "Employee number is required"), // generated, but required in payload
  first_name: z.string().min(1, "First name is required"),
  last_name: z.string().min(1, "Last name is required"),
  email: z.string().email("Email must be valid"),
  contact_number: z.string().optional().or(z.literal("")),
  department: z.string().min(1, "Department is required"),
  position: z.string().min(1, "Position is required"),
  status: z.string().min(1, "Status is required"),
  is_archived: z.boolean().default(false),
});

async function generateEmployeeNumber() {
  const year2 = String(new Date().getFullYear()).slice(-2); // "25"
  const prefix = `T${year2}-`; // "T25-"

  const { data, error } = await supabase
    .from("teachers")
    .select("employee_number")
    .ilike("employee_number", `${prefix}%`)
    .order("employee_number", { ascending: false })
    .limit(1);

  if (error) throw error;

  const last = data?.[0]?.employee_number; // e.g. "T25-0007"

  // ✅ safest parsing: last 4 digits
  const lastNum = last ? parseInt(String(last).slice(-4), 10) : 0;

  const nextNum = lastNum + 1;
  const padded = String(nextNum).padStart(4, "0"); // "0008"

  return `${prefix}${padded}`; // "T25-0008"
}

export default function Management() {
  const qc = useQueryClient();

  const [q, setQ] = useState("");
  const [modal, setModal] = useState({ open: false, mode: "create", row: null });

  const teachersQ = useQuery({
    queryKey: ["teachers"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("teachers")
        .select("*")
        .order("updated_at", { ascending: false });

      if (error) throw error;
      return data ?? [];
    },
  });

  const rows = teachersQ.data ?? [];

  const filtered = useMemo(() => {
    const needle = q.trim().toLowerCase();
    if (!needle) return rows;

    return rows.filter((r) => {
      const hay =
        `${r.employee_number || ""} ${r.department || ""} ${r.position || ""} ${r.status || ""} ` +
        `${r.first_name || ""} ${r.last_name || ""} ${r.email || ""} ${r.contact_number || ""}`.toLowerCase();
      return hay.includes(needle);
    });
  }, [rows, q]);

  // CREATE
  const createM = useMutation({
    mutationFn: async (values) => {
      // IMPORTANT: user_id is generated by system (auth) and should be set server-side.
      // If your DB requires user_id (PK), you must insert it from the logged-in user:
      const {
        data: { user },
        error: userErr,
      } = await supabase.auth.getUser();
      if (userErr) throw userErr;
      if (!user) throw new Error("No authenticated user found.");

      const payload = {
        user_id: user.id, // system-generated auth UUID
        employee_number: values.employee_number, // generated
        department: values.department,
        position: values.position,
        status: values.status,

        first_name: values.first_name,
        last_name: values.last_name,
        email: values.email,
        contact_number: values.contact_number ? values.contact_number : null,
        is_archived: values.is_archived ?? false,
      };

      const { error } = await supabase.from("teachers").insert(payload);
      if (error) throw error;
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ["teachers"] }),
  });

  // UPDATE (PK is user_id)
  const updateM = useMutation({
    mutationFn: async ({ user_id, values }) => {
      const payload = {
        // employee_number NOT editable (do not update)
        department: values.department,
        position: values.position,
        status: values.status,

        first_name: values.first_name,
        last_name: values.last_name,
        email: values.email,
        contact_number: values.contact_number ? values.contact_number : null,
        is_archived: values.is_archived ?? false,
      };

      const { error } = await supabase
        .from("teachers")
        .update(payload)
        .eq("user_id", user_id);

      if (error) throw error;
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ["teachers"] }),
  });

  // ARCHIVE / UNARCHIVE (recommended instead of delete)
  const archiveM = useMutation({
    mutationFn: async ({ user_id, is_archived }) => {
      const { error } = await supabase
        .from("teachers")
        .update({ is_archived })
        .eq("user_id", user_id);
      if (error) throw error;
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ["teachers"] }),
  });

  // HARD DELETE (optional)
  const deleteM = useMutation({
    mutationFn: async (user_id) => {
      const { error } = await supabase.from("teachers").delete().eq("user_id", user_id);
      if (error) throw error;
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ["teachers"] }),
  });

  async function openCreate() {
    try {
      const employee_number = await generateEmployeeNumber();
      setModal({ open: true, mode: "create", row: { employee_number } });
    } catch (e) {
      alert(`Failed to generate employee number: ${String(e?.message || e)}`);
    }
  }

  function openView(row) {
    setModal({ open: true, mode: "view", row });
  }
  function openEdit(row) {
    setModal({ open: true, mode: "edit", row });
  }
  function closeModal() {
    setModal({ open: false, mode: "create", row: null });
  }

  function onArchiveToggle(row) {
    archiveM.mutate({ user_id: row.user_id, is_archived: !row.is_archived });
  }

  function onDelete(row) {
    const ok = window.confirm(
      `Hard delete teacher ${row.employee_number}? (This cannot be undone)`
    );
    if (!ok) return;
    deleteM.mutate(row.user_id);
  }

  return (
    <div className="space-y-4">
      <div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between">
        <div>
          <div className="text-sm font-extrabold">Teacher • Management</div>
          <div className="text-xs text-black/55">
            Add, view, update, and archive teacher records.
          </div>
        </div>

        <button
          onClick={openCreate}
          className={`inline-flex items-center gap-2 rounded-2xl px-4 py-2 text-sm font-extrabold ${TOKENS.goldBg} text-black hover:opacity-95`}
        >
          <Plus className="h-4 w-4" />
          Add Teacher
        </button>
      </div>

      {/* Search */}
      <div className="rounded-2xl border border-black/10 bg-white/60 p-4">
        <div className="relative md:max-w-md">
          <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-black/45" />
          <input
            value={q}
            onChange={(e) => setQ(e.target.value)}
            placeholder="Search name, email, employee #, department, status…"
            className="w-full rounded-2xl border border-black/10 bg-white/70 px-10 py-2 text-sm outline-none focus:bg-white"
          />
        </div>
      </div>

      {/* Table */}
      <div className="overflow-hidden rounded-2xl border border-black/10 bg-white/70">
        <div className="flex items-center justify-between border-b border-black/10 bg-black/[0.02] px-4 py-3">
          <div className="text-sm font-extrabold">Teachers</div>
          <div className="text-xs text-black/55">
            Showing {filtered.length} of {rows.length}
          </div>
        </div>

        {teachersQ.isLoading ? (
          <div className="p-6 text-sm text-black/60">Loading…</div>
        ) : teachersQ.isError ? (
          <div className="p-6 text-sm text-rose-700">
            Error: {String(teachersQ.error?.message || teachersQ.error)}
          </div>
        ) : (
          <table className="w-full text-left text-sm">
            <thead className="bg-black/[0.03] text-xs text-black/60">
              <tr>
                <th className="px-4 py-3 font-semibold">Employee #</th>
                <th className="px-4 py-3 font-semibold">Name</th>
                <th className="px-4 py-3 font-semibold">Email</th>
                <th className="px-4 py-3 font-semibold">Contact</th>
                <th className="px-4 py-3 font-semibold">Department</th>
                <th className="px-4 py-3 font-semibold">Position</th>
                <th className="px-4 py-3 font-semibold">Status</th>
                <th className="px-4 py-3 font-semibold">Archived</th>
                <th className="px-4 py-3 font-semibold text-right">Actions</th>
              </tr>
            </thead>
            <tbody>
              {filtered.map((r) => (
                <tr key={r.user_id} className="border-t border-black/10">
                  <td className="px-4 py-3 font-semibold">{r.employee_number}</td>
                  <td className="px-4 py-3 font-semibold">
                    {r.last_name}, {r.first_name}
                  </td>
                  <td className="px-4 py-3 text-black/70">{r.email || "-"}</td>
                  <td className="px-4 py-3 text-black/70">
                    {r.contact_number || "-"}
                  </td>
                  <td className="px-4 py-3 text-black/70">{r.department}</td>
                  <td className="px-4 py-3 text-black/70">{r.position}</td>
                  <td className="px-4 py-3">
                    <StatusPill value={r.status} />
                  </td>
                  <td className="px-4 py-3 text-black/70">
                    {r.is_archived ? "Yes" : "No"}
                  </td>
                  <td className="px-4 py-3">
                    <div className="flex justify-end gap-2">
                      <IconBtn title="View" onClick={() => openView(r)} tone="neutral">
                        <Eye className="h-5 w-5" />
                      </IconBtn>
                      <IconBtn title="Edit" onClick={() => openEdit(r)} tone="gold">
                        <Pencil className="h-5 w-5" />
                      </IconBtn>
                      <IconBtn
                        title={r.is_archived ? "Unarchive" : "Archive"}
                        onClick={() => onArchiveToggle(r)}
                        tone="neutral"
                      >
                        <ArchiveRestore className="h-5 w-5" />
                      </IconBtn>

                      {/* Optional hard delete */}
                      <IconBtn title="Delete" onClick={() => onDelete(r)} tone="danger">
                        <Trash2 className="h-5 w-5" />
                      </IconBtn>
                    </div>
                  </td>
                </tr>
              ))}

              {filtered.length === 0 ? (
                <tr>
                  <td colSpan={9} className="px-4 py-10 text-center text-sm text-black/55">
                    No teachers found.
                  </td>
                </tr>
              ) : null}
            </tbody>
          </table>
        )}
      </div>

      {modal.open ? (
        <TeacherModal
          mode={modal.mode}
          row={modal.row}
          onClose={closeModal}
          onCreate={(values) => createM.mutate(values)}
          onUpdate={(user_id, values) => updateM.mutate({ user_id, values })}
          busy={createM.isPending || updateM.isPending}
        />
      ) : null}
    </div>
  );
}

function TeacherModal({ mode, row, onClose, onCreate, onUpdate, busy }) {
  const isView = mode === "view";
  const isEdit = mode === "edit";

  const defaults = useMemo(() => {
    const base = {
      employee_number: "",
      department: "",
      position: "",
      status: "Active",

      first_name: "",
      last_name: "",
      email: "",
      contact_number: "",
      is_archived: false,
    };

    if (!row) return base;

    return {
      employee_number: row.employee_number ?? "",
      department: row.department ?? "",
      position: row.position ?? "",
      status: row.status ?? "Active",

      first_name: row.first_name ?? "",
      last_name: row.last_name ?? "",
      email: row.email ?? "",
      contact_number: row.contact_number ?? "",
      is_archived: !!row.is_archived,
    };
  }, [row]);

  const form = useForm({
    resolver: zodResolver(teacherSchema),
    defaultValues: defaults,
    values: defaults,
  });

  const { register, handleSubmit, formState } = form;
  const { errors } = formState;

  function submit(values) {
    if (isEdit) onUpdate(row.user_id, values);
    if (!isView && !isEdit) onCreate(values);
    onClose();
  }

  return (
    <>
      <div className="fixed inset-0 z-40 bg-black/25" onClick={onClose} />
      <div
        className={`fixed right-4 top-4 bottom-4 z-50 w-[92vw] max-w-xl rounded-2xl border ${TOKENS.border} ${TOKENS.panel} shadow-xl`}
      >
        <div className="flex items-center justify-between border-b border-black/10 p-4">
          <div>
            <div className="text-sm font-extrabold">
              {isView ? "View Teacher" : isEdit ? "Edit Teacher" : "Add Teacher"}
            </div>
            <div className="text-xs text-black/55">
              employee # and user_id are system-generated (not editable).
            </div>
          </div>

          <button
            onClick={onClose}
            className="grid h-9 w-9 place-items-center rounded-2xl hover:bg-black/5"
          >
            <X className="h-5 w-5 text-black/60" />
          </button>
        </div>

        <form
          onSubmit={handleSubmit(submit)}
          className="h-[calc(100%-64px)] overflow-auto p-4 space-y-4"
        >
          <div className="rounded-2xl border border-black/10 bg-white/70 p-4">
            <div className={`text-sm font-extrabold ${TOKENS.brown}`}>
              Teacher Info
            </div>

            <div className="mt-3 grid gap-3 md:grid-cols-2">
              {/* Employee number is generated, not editable */}
              <Input
                label="Employee Number"
                disabled={true}
                error={errors.employee_number?.message}
                {...register("employee_number")}
              />

              <Input
                label="First Name *"
                disabled={isView}
                error={errors.first_name?.message}
                {...register("first_name")}
              />
              <Input
                label="Last Name *"
                disabled={isView}
                error={errors.last_name?.message}
                {...register("last_name")}
              />

              <Input
                label="Email *"
                disabled={isView}
                error={errors.email?.message}
                {...register("email")}
              />
              <Input
                label="Contact Number"
                disabled={isView}
                error={errors.contact_number?.message}
                {...register("contact_number")}
              />

              <Input
                label="Department *"
                disabled={isView}
                error={errors.department?.message}
                {...register("department")}
              />
              <Input
                label="Position *"
                disabled={isView}
                error={errors.position?.message}
                {...register("position")}
              />

              <Select
                label="Status *"
                disabled={isView}
                error={errors.status?.message}
                {...register("status")}
              >
                <option value="Active">Active</option>
                <option value="Inactive">Inactive</option>
                <option value="On Leave">On Leave</option>
              </Select>

              <label className="flex items-center gap-2 rounded-2xl border border-black/10 bg-white/70 px-3 py-2 text-sm">
                <input type="checkbox" disabled={isView} {...register("is_archived")} />
                Archived
              </label>
            </div>
          </div>

          <div className="flex items-center justify-end gap-2">
            <button
              type="button"
              onClick={onClose}
              className="rounded-2xl border border-black/10 bg-white/70 px-4 py-2 text-sm font-semibold hover:bg-white"
            >
              Close
            </button>

            {!isView ? (
              <button
                disabled={busy}
                type="submit"
                className={`inline-flex items-center gap-2 rounded-2xl px-4 py-2 text-sm font-extrabold ${TOKENS.goldBg} text-black hover:opacity-95 disabled:opacity-60`}
              >
                <Save className="h-4 w-4" />
                {isEdit ? "Save Changes" : "Create Teacher"}
              </button>
            ) : null}
          </div>
        </form>
      </div>
    </>
  );
}

function StatusPill({ value }) {
  const v = String(value || "").toLowerCase();
  const cls =
    v === "active"
      ? "bg-emerald-500/10 text-emerald-700"
      : v === "inactive"
      ? "bg-rose-500/10 text-rose-700"
      : "bg-[#6B4E2E]/10 text-[#6B4E2E]";

  return (
    <span className={`inline-flex rounded-full px-3 py-1 text-xs font-semibold ${cls}`}>
      {value || "-"}
    </span>
  );
}

function IconBtn({ title, onClick, tone, children }) {
  const cls =
    tone === "danger"
      ? "bg-rose-500/10 text-rose-700 hover:bg-rose-500/15"
      : tone === "gold"
      ? "bg-[#C9A227]/10 text-[#C9A227] hover:opacity-90"
      : "bg-white/70 text-black/65 hover:bg-white";

  return (
    <button
      title={title}
      onClick={onClick}
      className={`grid h-9 w-9 place-items-center rounded-2xl border border-black/10 ${cls}`}
    >
      {children}
    </button>
  );
}

function Input({ label, error, disabled, ...rest }) {
  return (
    <label className="block">
      <span className="text-xs font-semibold text-black/55">{label}</span>
      <input
        disabled={disabled}
        {...rest}
        className="mt-1 w-full rounded-2xl border border-black/10 bg-white/70 px-3 py-2 text-sm outline-none focus:bg-white disabled:opacity-60"
      />
      {error ? <div className="mt-1 text-xs text-rose-700">{error}</div> : null}
    </label>
  );
}

function Select({ label, error, disabled, children, ...rest }) {
  return (
    <label className="block">
      <span className="text-xs font-semibold text-black/55">{label}</span>
      <select
        disabled={disabled}
        {...rest}
        className="mt-1 w-full rounded-2xl border border-black/10 bg-white/70 px-3 py-2 text-sm outline-none focus:bg-white disabled:opacity-60"
      >
        {children}
      </select>
      {error ? <div className="mt-1 text-xs text-rose-700">{error}</div> : null}
    </label>
  );
}
